BaseUrl=http://localhost:8111
api=/app/rest

admin.login=admin
admin.password=admin

vcsRootName = jetbrains.git
vcsPropertyName = url
vcsPropertyValue = https://github.com/org/repo.git
vcsId = _Root

ui.baseUrl=http://localhost:8111
uiRemote=

browser=chrome
browser.size=1920x1080

teamcity.agent.1.name=tc-agent-1
teamcity.agent.2.name=tc-agent-2