name: run-tests.yml
on:
  workflow_dispatch:
  push:
    branches: [ create-teamcity-profile ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      TEAMCITY_DATA_TAG: teamcity-data
      TEAMCITY_DATA_ASSET: teamcity-data.tar.gz

    steps:
      - uses: actions/checkout@v4

      - name: Download asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download "$TEAMCITY_DATA_TAG" \
            --pattern "$TEAMCITY_DATA_ASSET" \
            --output "$TEAMCITY_DATA_ASSET"

      - name: Extract
        run: |
          tar -xzf "$TEAMCITY_DATA_ASSET" -C infra
          ls -la infra
          ls -la infra/teamcity-data

      - name: Fix permissions
        run: |
          sudo chown -R 1000:1000 infra/teamcity-data

      - name: Set env
        working-directory: ./infra
        run: cp .env.example .env

      - name: Start TeamCity
        working-directory: ./infra
        run: docker compose up -d

      - name: Wait for TeamCity
        run: |
          timeout 600 bash -c '
            until curl -fsS http://localhost:8111/mnt/get/currentState > /dev/null; do
              sleep 5
            done
          '
      - name: Show TeamCity logs
        if: failure()
        working-directory: ./infra
        run: docker compose logs teamcity-server

      - name: Stop
        working-directory: ./infra
        if: always()
        run: docker compose down -v
