name: run-tests.yml
on:
  workflow_dispatch:
  push:
    branches: [ create-teamcity-profile ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      TEAMCITY_DATA_TAG: teamcity-data
      TEAMCITY_DATA_ASSET: teamcity-data.tar.gz

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Download asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download "$TEAMCITY_DATA_TAG" \
            --pattern "$TEAMCITY_DATA_ASSET" \
            --output "$TEAMCITY_DATA_ASSET"

      - name: Extract
        run: |
          tar -xzf "$TEAMCITY_DATA_ASSET" -C infra
          ls -la infra
          ls -la infra/teamcity-data

      - name: Fix permissions
        run: |
          sudo chown -R 1000:1000 infra/teamcity-data

      - name: Set env
        working-directory: ./infra
        run: cp .env.example .env

      - name: Cache Maven repository # Кэширование репозитория Maven для ускорения сборки
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up services # Настройка сервисов, например, запуск Docker контейнеров
        run: cd infra && bash restart_docker.sh selenoid && cd ..

      - name: Wait for TeamCity
        run: |
          timeout 600 bash -c '
            until curl -fsS http://localhost:8111/login.html > /dev/null; do
              sleep 10
            done
          '

      - name: Run tests
        run: |
          mvn test -Pselenoid 

      - name: Generate Allure report
        if: always()
        run: |
          mvn allure:report

      - name: Upload Allure artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-artifacts
          path: |
            allure-results
            target/site/allure-maven-plugin
          if-no-files-found: ignore

      - name: Stop
        working-directory: ./infra
        if: always()
        run: docker compose down -v
